# Generated by Django 3.1.14 on 2023-02-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800)),
                ('answer_method', models.CharField(choices=[('None', 'None'), ('Radio-Button', 'Radio-Button'), ('Check-Box', 'Check-Box')], max_length=50)),
                ('other_method', models.BooleanField()),
                ('date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trusthelpdesk.question')),
            ],
        ),
    ]
