# Generated by Django 3.1.14 on 2023-02-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trusthelpdesk', '0003_auto_20230226_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=500)),
                ('issues', models.TextField()),
                ('more_issue', models.TextField()),
                ('full_information_issue', models.TextField()),
                ('phrase', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
