# Generated by Django 3.1.14 on 2023-02-26 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trusthelpdesk', '0004_uanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UAnswer',
            new_name='UsersInfo',
        ),
    ]
